amqp:
  admin:
    auto-create: ${AMQP_ADMIN_AUTO_CREATE}
  host: ${AMQP_RABBIT_HOST}
  port: ${AMQP_RABBIT_PORT}
  username: ${AMQP_RABBIT_USERNAME}
  password: ${AMQP_RABBIT_PASSWORD}

mysql:
  username: ${DATABASE_MYSQL_USERNAME}
  password: ${DATABASE_MYSQL_PASSWORD}
  schema: ${DATABASE_MYSQL_SCHEMA}
  url: ${DATABASE_MYSQL_URL}


  spring:
    jpa:
      show-sql: false
      hibernate:
        ddl-auto: none